export const CREATE_ISSUE = "CREATE_ISSUE";
export const LOAD_ISSUES_SUCCESS = "LOAD_ISSUES_SUCCESS";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
